base_url: "https://v2.cropin.co.in/qa1"
login_endpoint: "/auth/v1/login"
timeout_ms: 30000
default_headers:
  Content-Type: "application/json"
  Accept: "application/json"
sso_base_url: "https://v2sso-gcp.cropin.co.in"
